{
 "title": "OT Dash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((min(up{nodename!='', nodename!~\".*staging.*\"}) by (nodename) * max(up{nodename!='', nodename!~\".*staging.*\"}) by (nodename)),\n  \"short_node\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{ short_node }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  (1 - avg by(node) (rate(node_cpu_seconds_total{mode=\"idle\", nodename!~\".*staging.*\"}[5m]))),\n  \"short_node\",\n  \"$1\",\n  \"node\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{ short_node }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  (\n    (node_memory_MemTotal_bytes{nodename!~\".*staging.*\"} - node_memory_MemAvailable_bytes{nodename!~\".*staging.*\"})/node_memory_MemTotal_bytes{nodename!~\".*staging.*\"}\n    and on(nodename) (up @ end() == 1)\n  ),\n  \"short_node\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{short_node}}"
    }
   ]
  },
  {
   "title": "Requests source",
   "type": "geomap",
   "description": "Gives a broad vision of where the requests are being done ",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"api\"} |= `client_ip` | json | line_format `{{.geoip_country_code}}`"
    }
   ]
  },
  {
   "title": "Top 10 queries Increase",
   "type": "bargauge",
   "description": "Top 10 queries in the last period",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by(query_name) (increase(platform_api_graphql_requests_total{node_environment=\"production\", query_name!=\"\"}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log level API",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"api\"}  | detected_level != \"\"       [$__auto])) by (detected_level)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Top 5 Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by(geoip_continent_code) (count_over_time({container=\"api\"} |= `client_ip` | json [$__auto])))"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Heap memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  jvm_memory_used_bytes{area=\"heap\", node_environment=\"production\"} / jvm_memory_max_bytes{area=\"heap\", node_environment=\"production\"},\n  \"short_node\",\n  \"$1\",\n  \"node\",\n  \".*-([^-]+)$\"\n)\n",
     "legendFormat": "{{ short_node }}"
    }
   ]
  },
  {
   "title": "Max Heap Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n\nlabel_replace(\n  jvm_memory_max_bytes{area=\"heap\", node_environment=\"production\"},\n  \"short_node\",\n  \"$1\",\n  \"node\",\n  \".*-([^-]+)$\"\n)\n",
     "legendFormat": "{{ short_node }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "CPU load as the % of the total available cores usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    irate(\n        process_cpu_seconds_total{app=\"api\",node_environment=\"production\"}[5m]) / on() group_left() count(node_cpu_seconds_total{mode=\"idle\",node_environment=\"production\"}\n    ) * 100,\n    \"instance_no_port\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+):.*\"\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM heap",
   "type": "timeseries",
   "description": "JVM Heap memory usage as the % of the deployment maximum RAM resource allocation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", node_environment=\"production\"} / jvm_memory_max_bytes{area=\"heap\", node_environment=\"production\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GraphQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance)(rate(platform_api_graphql_requests_total{node_environment=\"production\"}[5m]))\n  and on(instance) up == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (database)(rate(platform_api_db_query_total{node_environment=\"production\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit per query name",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,\n  (1 - \n    sum by(query_name) (rate(platform_api_cache_missed_total{query_name!=\"\", node_environment=\"production\"}[$__range]))\n    /\n    sum by(query_name) (rate(platform_api_graphql_requests_total{query_name!=\"\", node_environment=\"production\"}[$__range]))\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - \n  sum(rate(platform_api_cache_missed_total{node_environment=\"production\"}[5m]))\n  /\n  sum(rate(platform_api_graphql_requests_total{node_environment=\"production\"}[5m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "k8s nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n  (1 - avg by(nodename) (irate(node_cpu_seconds_total{mode=\"idle\", nodename!=\"\"}[5m]))) * 100,\n  \"short_nodename\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{ short_nodename }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  (node_memory_MemTotal_bytes{nodename!=\"\"} - node_memory_MemAvailable_bytes{nodename!=\"\"})/node_memory_MemTotal_bytes{nodename!=\"\"},\n  \"short_nodename\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{ short_nodename }}"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(nodename) (rate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[5m])),\n  \"short_nodename\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{short_nodename}} ↓"
    },
    {
     "expr": "label_replace(\n  -sum by(nodename) (rate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\"}[5m])),\n  \"short_nodename\",\n  \"$1\",\n  \"nodename\",\n  \".*-([^-]+)$\"\n)",
     "legendFormat": "{{short_nodename}} ↑"
    }
   ]
  },
  {
   "title": "Traffic drop",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by (nodename) (rate(node_network_receive_drop_total{job=\"kubernetes-service-endpoints\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}