# Namespace
{{ include "common.namespace" . }}

{{- if include "isDeploymentUsed" (dict "root" . "color" "blue") }}
# Blue deployment components
{{ include "common.networkpolicy" (dict "root" . "color" "blue") }}
{{ include "external.clickhouse" (dict "root" . "color" "blue") }}
{{ include "external.opensearch" (dict "root" . "color" "blue") }}
{{ include "deployment.api" (dict "root" . "color" "blue") }}
{{ include "deployment.aiapi" (dict "root" . "color" "blue") }}
{{ include "deployment.webapp" (dict "root" . "color" "blue") }}
{{- end }}

{{- if include "isDeploymentUsed" (dict "root" . "color" "green") }}
# Green deployment components
{{ include "common.networkpolicy" (dict "root" . "color" "green") }}
{{ include "external.clickhouse" (dict "root" . "color" "green") }}
{{ include "external.opensearch" (dict "root" . "color" "green") }}
{{ include "deployment.api" (dict "root" . "color" "green") }}
{{ include "deployment.aiapi" (dict "root" . "color" "green") }}
{{ include "deployment.webapp" (dict "root" . "color" "green") }}
{{- end }}

# Production services
{{ include "service.api" (dict "root" . "env" "prod") }}
{{ include "service.aiapi" (dict "root" . "env" "prod") }}
{{ include "service.webapp" (dict "root" . "env" "prod") }}
{{ include "common.ingress" (dict "root" . "env" "prod") }}

# Staging services
{{ include "service.api" (dict "root" . "env" "staging") }}
{{ include "service.aiapi" (dict "root" . "env" "staging") }}
{{ include "service.webapp" (dict "root" . "env" "staging") }}
{{ include "common.ingress" (dict "root" . "env" "staging") }}
