# Common components
{{ include "common.networkpolicy" . }}

# Platform components
{{ include "deployment.api" . }}
{{ include "deployment.aiapi" . }}
{{ include "deployment.webapp" . }}
{{ include "statefulset.clickhouse" . }}
{{ include "statefulset.opensearch" . }}

# Services
{{ include "service.api" . }}
{{ include "service.aiapi" . }}
{{ include "service.webapp" . }}
{{ include "service.clickhouse" . }}
{{ include "service.opensearch" . }}
