{{ define "service.webapp" }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $namespace }} WebApp.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-webapp
  namespace: {{ $namespace }}
  labels:
    app: webapp
    {{- $labels | nindent 4 }}
  {{- if .Values.gcp.enabled }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-backendconfig-cdn"}'
  {{- end }}
spec:
  selector:
    app: webapp
  ports:
    - port: {{ include "ports.http" . }}
      targetPort: {{ include "ports.http" . }}
      protocol: TCP
      name: http
  type: NodePort
{{- end }}


{{ define "service.api" }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $namespace }} API.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-api
  namespace: {{ $namespace }}
  labels:
    app: api
    {{- $labels | nindent 4 }}
  annotations:
    {{- if .Values.gcp.enabled }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-backendconfig-no-cdn"}'
    {{- end }}
    prometheus.io/scrape: {{ if eq .Values.product "platform" }}"true"{{ else }}"false"{{ end }}
spec:
  selector:
    app: api
  ports:
    - port: {{ include "ports.http" . }}
      targetPort: {{ include "ports.http" . }}
      protocol: TCP
      name: api
  type: NodePort
{{- end }}


{{ define "service.aiapi" }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $namespace }} AI API.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-aiapi
  namespace: {{ $namespace }}
  labels:
    app: aiapi
    {{- $labels | nindent 4 }}
  {{- if .Values.gcp.enabled }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-backendconfig-no-cdn"}'
  {{- end }}
spec:
  selector:
    app: aiapi
  ports:
    - port: {{ include "ports.http" . }}
      targetPort: {{ include "ports.http" . }}
      protocol: TCP
      name: aiapi
  type: NodePort
{{- end }}


{{ define "service.clickhouse" }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $namespace }} ClickHouse.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-clickhouse
  namespace: {{ $namespace }}
  labels:
    app: clickhouse
    {{- $labels | nindent 4 }}
  annotations:
    prometheus.io/scrape: {{ if eq .Values.product "platform" }}"true"{{ else }}"false"{{ end }}
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - port: {{ include "ports.clickhouse" . }}
      targetPort: {{ include "ports.clickhouse" . }}
      name: http
    - port: {{ include "ports.clickhouse.native" . }}
      targetPort: {{ include "ports.clickhouse.native" . }}
      name: native
    - port: {{ include "ports.clickhouse.metrics" . }}
      targetPort: {{ include "ports.clickhouse.metrics" . }}
      name: metrics
{{- end }}


{{ define "service.opensearch" }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $namespace }} OpenSearch.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-opensearch
  namespace: {{ $namespace }}
  labels:
    app: opensearch
    {{- $labels | nindent 4 }}
  annotations:
    prometheus.io/scrape: {{ if eq .Values.product "platform" }}"true"{{ else }}"false"{{ end }}
spec:
  type: ClusterIP
  selector:
    app: opensearch
  ports:
    - port: {{ include "ports.opensearch" . }}
      targetPort: {{ include "ports.opensearch" . }}
      name: http
    - port: {{ include "ports.opensearch.perf" . }}
      targetPort: {{ include "ports.opensearch.perf" . }}
      name: perfanalyzer
{{- end }}
