{{ define "service.webapp" }}
{{- $root := .root }}
{{- $env := .env | default "prod" }}
{{- $namespace := include "prefix-product" .root }}
{{- $labels := include "labels" .root }}
{{- $deploymentColor := include "deploymentColor" (dict "root" .root "env" .env) -}}
---
# Service for {{ $namespace }}-{{ $env }} webapp.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $env }}-webapp
  namespace: {{ $namespace }}
  labels:
    app: webapp
    environment: {{ $env }}
    {{- $labels | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-{{ $env }}-backendconfig-cdn"}'
spec:
  selector:
    app: webapp
    color: {{ $deploymentColor }}
  ports:
    - port: {{ include "ports.http" $root }}
      targetPort: {{ include "ports.http" $root }}
      protocol: TCP
      name: http
  type: NodePort
{{- end }}


{{ define "service.api" }}
{{- $root := .root }}
{{- $env := .env | default "prod" }}
{{- $namespace := include "prefix-product" .root }}
{{- $labels := include "labels" .root }}
{{- $deploymentColor := include "deploymentColor" (dict "root" .root "env" .env) -}}
---
# Service for {{ $namespace }}-{{ $env }} API.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $env }}-api
  namespace: {{ $namespace }}
  labels:
    app: api
    environment: {{ $env }}
    {{- $labels | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-{{ $env }}-backendconfig-no-cdn"}'
    prometheus.io/scrape: {{ if eq $env "prod" }}"true"{{ else }}"false"{{ end }}
spec:
  selector:
    app: api
    color: {{ $deploymentColor }}
  ports:
    - port: {{ include "ports.http" $root }}
      targetPort: {{ include "ports.apiproxy" $root }}
      protocol: TCP
      name: api
  type: NodePort
{{- end }}


{{ define "service.aiapi" }}
{{- $root := .root }}
{{- $env := .env | default "prod" }}
{{- $namespace := include "prefix-product" .root }}
{{- $labels := include "labels" .root }}
{{- $deploymentColor := include "deploymentColor" (dict "root" .root "env" .env) -}}
---
# Service for {{ $namespace }}-{{ $env }} AI API.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $env }}-aiapi
  namespace: {{ $namespace }}
  labels:
    app: aiapi
    environment: {{ $env }}
    {{- $labels | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ $namespace }}-{{ $env }}-backendconfig-no-cdn"}'
spec:
  selector:
    app: aiapi
    color: {{ $deploymentColor }}
  ports:
    - port: {{ include "ports.http" $root }}
      targetPort: {{ include "ports.http" $root }}
      protocol: TCP
      name: aiapi
  type: NodePort
{{- end }}


{{ define "service.clickhouse" }}
{{- $root := .root }}
{{- $env := .env | default "prod" }}
{{- $namespace := include "prefix-product" .root }}
{{- $labels := include "labels" .root }}
{{- $deploymentColor := include "deploymentColor" (dict "root" .root "env" .env) -}}
---
# Service for {{ $namespace }}-{{ $env }} ClickHouse.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $env }}-clickhouse
  namespace: {{ $namespace }}
  labels:
    app: clickhouse
    environment: {{ $env }}
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: clickhouse
    color: {{ $deploymentColor }}
  ports:
    - port: {{ include "ports.clickhouse" $root }}
      targetPort: {{ include "ports.clickhouse" $root }}
      name: http
    - port: 9000
      targetPort: 9000
      name: native
{{- end }}


{{ define "service.opensearch" }}
{{- $root := .root }}
{{- $env := .env | default "prod" }}
{{- $namespace := include "prefix-product" .root }}
{{- $labels := include "labels" .root }}
{{- $deploymentColor := include "deploymentColor" (dict "root" .root "env" .env) -}}
---
# Service for {{ $namespace }}-{{ $env }} OpenSearch.
apiVersion: v1
kind: Service
metadata:
  name: {{ $namespace }}-{{ $env }}-opensearch
  namespace: {{ $namespace }}
  labels:
    app: opensearch
    environment: {{ $env }}
    {{- $labels | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: opensearch
    color: {{ $deploymentColor }}
  ports:
    - port: {{ include "ports.opensearch" $root }}
      targetPort: {{ include "ports.opensearch" $root }}
      name: http
    - port: 9600
      targetPort: 9600
      name: metrics
{{- end }}


### TODO: DELETE AFTER 2603
{{ define "external.clickhouse" }}
{{- $prefix := .Values.prefix }}
{{- $product := .Values.product }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $prefix }} ClickHouse external service.
apiVersion: v1
kind: Service
metadata:
  name: {{ $prefix }}-clickhouse
  namespace: {{ $namespace }}
  labels:
    app: clickhouse
    {{- $labels | nindent 4 }}
spec:
  type: ExternalName
  externalName: clickhouse.{{ $prefix }}.internal
  ports:
    - port: {{ include "ports.clickhouse" . }}
      protocol: TCP
      name: clickhouse
{{- end }}


{{ define "external.opensearch" }}
{{- $prefix := .Values.prefix }}
{{- $product := .Values.product }}
{{- $namespace := include "prefix-product" . }}
{{- $labels := include "labels" . }}
---
# Service for {{ $prefix }} OpenSearch external service.
apiVersion: v1
kind: Service
metadata:
  name: {{ $prefix }}-opensearch
  namespace: {{ $namespace }}
  labels:
    app: opensearch
    {{- $labels | nindent 4 }}
spec:
  type: ExternalName
  externalName: opensearch.{{ $prefix }}.internal
  ports:
    - port: {{ include "ports.clickhouse" . }}
      protocol: TCP
      name: opensearch
{{- end }}
