apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devcluster-platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - colour: blue
          - colour: green
  template:
    metadata:
      name: devcluster-platform-{{ colour }}
    spec:
      project: default
      source:
        repoURL: https://github.com/opentargets/platform-deployment-nextgen.git
        targetRevision: argocd-nginx-router
        path: helm/platform
        helm:
          valueFiles:
            - /profiles/devcluster-{{ colour }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: devcluster-{{ colour }}-platform
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
