apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-platform
  namespace: argocd
spec:
  destination:
    namespace: local-platform
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - /profiles/local.yaml
    path: helm/platform
    repoURL: https://github.com/opentargets/platform-deployment-nextgen.git
    targetRevision: argocd
