apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
          - env: staging
  template:
    metadata:
      name: local-platform-{{ env }}
    spec:
      project: default
      source:
        repoURL: https://github.com/opentargets/platform-deployment-nextgen.git
        targetRevision: argocd
        path: helm/platform
        helm:
          valueFiles:
            - /profiles/local-{{ env }}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: local-{{ env }}-platform
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
