apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-platform-router
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opentargets/platform-deployment-nextgen.git
    targetRevision: argocd-nginx-router
    path: helm/router
    helm:
      valueFiles:
        - /profiles/local-router.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: local-platform
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
