---
# Shared namespace for all in-cluster databases
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    app.kubernetes.io/part-of: databases
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gcpProject }}


---
# StorageClass for Hyperdisk Balanced with {{ .Values.disk.iops }} IOPS and {{ .Values.disk.throughput }} MiB/s throughput.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-balanced
  annotations:
    helm.sh/resource-policy: keep
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
  provisioned-iops-on-create: {{ .Values.disk.iops | quote }}
  provisioned-throughput-on-create: {{ .Values.disk.throughput | quote }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


---
# NetworkPolicy to deny all traffic by default.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: databases
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress


---
# NetworkPolicy to allow API pods to reach the databases.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-ingress
  namespace: databases
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.prefix }}-platform
          podSelector:
            matchLabels:
              app: api
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.prefix }}-ppp
          podSelector:
            matchLabels:
              app: api
      ports:
        - protocol: TCP
          port: 8123    # ClickHouse HTTP
        - protocol: TCP
          port: 9000    # ClickHouse native protocol


---
# NetworkPolicy to allow all egress traffic from databases (DNS + HTTPS only).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: databases
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
