{
 "title": "OT Dash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{nodename!=''}) by (nodename) * max(up{nodename!=''}) by (nodename)",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  { "title": "QuickView CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__range])))",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  { "title": "QuickView Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  {
   "title": "API Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GraphQL Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(nodename)(rate(platform_api_graphql_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Heap Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (database)(rate(platform_api_db_query_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Queries",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(query_name) (platform_api_graphql_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU Usage Per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename!=\"\"}[$__range])))",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{nodename!=\"\"} - node_memory_MemAvailable_bytes{nodename!=\"\"})/node_memory_MemTotal_bytes{nodename!=\"\"}",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Network Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename)(rate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[$__range]))",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  {
   "title": "Network Outgoing Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (nodename)(rate(node_network_transmit_packets_total{job=\"kubernetes-service-endpoints\"}[$__range]))",
     "legendFormat": "{{`{{nodename}}`}}"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by (nodename) (rate(node_network_receive_drop_total{job=\"kubernetes-service-endpoints\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}